package com.persistance.model;

// Generated 7 mars 2016 19:36:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bonsortie generated by hbm2java
 */
@Entity
@Table(name = "bonsortie", catalog = "gestionstock")
public class Bonsortie implements java.io.Serializable {

	private int idsortie;
	private Stock stock=new Stock();
	private Utilisateur utilisateur=new Utilisateur();
	private Date datesortie;
	private int prixunitaire;
	private Integer quantite;

	public Bonsortie() {
	}

	public Bonsortie(int idsortie, Stock stock, int prixunitaire) {
		this.idsortie = idsortie;
		this.stock = stock;
		this.prixunitaire = prixunitaire;
	}

	public Bonsortie(int idsortie, Stock stock, Utilisateur utilisateur,
			Date datesortie, int prixunitaire, Integer quantite) {
		this.idsortie = idsortie;
		this.stock = stock;
		this.utilisateur = utilisateur;
		this.datesortie = datesortie;
		this.prixunitaire = prixunitaire;
		this.quantite = quantite;
	}

	@Id
	@Column(name = "IDSortie", unique = true, nullable = false)
	public int getIdsortie() {
		return this.idsortie;
	}

	public void setIdsortie(int idsortie) {
		this.idsortie = idsortie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "refP", nullable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "agent")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datesortie", length = 0)
	public Date getDatesortie() {
		return this.datesortie;
	}

	public void setDatesortie(Date datesortie) {
		this.datesortie = datesortie;
	}

	@Column(name = "prixunitaire", nullable = false)
	public int getPrixunitaire() {
		return this.prixunitaire;
	}

	public void setPrixunitaire(int prixunitaire) {
		this.prixunitaire = prixunitaire;
	}

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

}
