package com.persistance.model;

// Generated 7 mars 2016 19:36:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "gestionstock")
public class Stock implements java.io.Serializable {

	private Integer idstock;
	private Categorie categorie=new Categorie();
	private Date dateentree;
	private Date datesortie;
	private String designation;
	private int prixunitaire;
	private Integer quantite;
	private Set<Bonsortie> bonsorties = new HashSet<Bonsortie>(0);
	private Set<Bonentree> bonentrees = new HashSet<Bonentree>(0);

	public Stock() {
	}

	

	@Id
	@Column(name = "IDStock", unique = true, nullable = false)
	public Integer getIdstock() {
		return this.idstock;
	}

	public void setIdstock(Integer idstock) {
		this.idstock = idstock;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategorie")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateentree", length = 0)
	public Date getDateentree() {
		return this.dateentree;
	}

	public void setDateentree(Date dateentree) {
		this.dateentree = dateentree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datesortie", length = 0)
	public Date getDatesortie() {
		return this.datesortie;
	}

	public void setDatesortie(Date datesortie) {
		this.datesortie = datesortie;
	}

	@Column(name = "designation")
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "prixunitaire", nullable = false)
	public int getPrixunitaire() {
		return this.prixunitaire;
	}

	public void setPrixunitaire(int prixunitaire) {
		this.prixunitaire = prixunitaire;
	}

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stock")
	public Set<Bonsortie> getBonsorties() {
		return this.bonsorties;
	}

	public void setBonsorties(Set<Bonsortie> bonsorties) {
		this.bonsorties = bonsorties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stock")
	public Set<Bonentree> getBonentrees() {
		return this.bonentrees;
	}

	public void setBonentrees(Set<Bonentree> bonentrees) {
		this.bonentrees = bonentrees;
	}

}
