package com.persistance.model;

// Generated 7 mars 2016 19:36:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "gestionstock")
public class Utilisateur implements java.io.Serializable {

	private int cin;
	private Role role=new Role();
	private String adresse;
	private String firstName;
	private String lastName;
	private String password;
	private Integer telephone;
	private String userName;
	private Set<Bonsortie> bonsorties = new HashSet<Bonsortie>(0);
	private Set<Bonentree> bonentrees = new HashSet<Bonentree>(0);

	public Utilisateur() {
	}

	public Utilisateur(int cin) {
		this.cin = cin;
	}

	public Utilisateur(int cin, Role role, String adresse, String firstName,
			String lastName, String password, Integer telephone,
			String userName, Set<Bonsortie> bonsorties, Set<Bonentree> bonentrees) {
		this.cin = cin;
		this.role = role;
		this.adresse = adresse;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.telephone = telephone;
		this.userName = userName;
		this.bonsorties = bonsorties;
		this.bonentrees = bonentrees;
	}

	@Id
	@Column(name = "cin", unique = true, nullable = false)
	public int getCin() {
		return this.cin;
	}

	public void setCin(int cin) {
		this.cin = cin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idrole")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "adresse")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "firstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "telephone")
	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	@Column(name = "userName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Bonsortie> getBonsorties() {
		return this.bonsorties;
	}

	public void setBonsorties(Set<Bonsortie> bonsorties) {
		this.bonsorties = bonsorties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Bonentree> getBonentrees() {
		return this.bonentrees;
	}

	public void setBonentrees(Set<Bonentree> bonentrees) {
		this.bonentrees = bonentrees;
	}

}
